project:
  type: website
  output-dir: docs
  
website:
  title: "CSEE Inferencia 2, temas 1 a 8 de modelización"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - T1_INTRO_GLM.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/luija85/GLM_CEE
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Luis Miguel Jáimez Rodríguez"

format:
  html:
    theme: cerulean
    toc: true

editor: source

